application: music-tutor
version: v100
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

libraries:
- name: webapp2
  version: latest

handlers:
- url: /static/img/*.png
  static_dir: static/img
  mime_type: image/png

- url: /static/*
  static_dir: static

- url: .*
  static_files: static/index.html
  upload: static/index.html

skip_files:
- ^node_modules/.*$
- ^js/.*$
- ^sass/.*$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.pyc$
